remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: "Leuck Family Reunion"
description: "June 26 to July 1 2023"
gitorg: "https://github.com/jm1021/leuck_reunion"
google_analytics:
